# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, modulesPath, ... }:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault false;
  networking = {
      interfaces."*" = {
        useDHCP = false;
        ipv4.addresses = [
          {
            address = "192.168.150.157"; # Replace with your desired static IP
            prefixLength = 24;         # Subnet mask (e.g., 24 for 255.255.255.0)
          }
        ];
      };
      nameservers = [ "8.8.8.8"  ]; # Replace with your preferred DNS servers
      defaultGateway.address = "192.168.150.100";
    };
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
